cloud:
  aws:
    region:
      static: us-east-2
    stack:
      auto: false
    credentials:
      access-key: 
      secret-key: 
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceFetcher: error
        util:
          EC2MetadataUtils: error
